export type AnswerPayload = string | string[] | { text: string; images: File[] };

export interface SurveyAnswers {
  [key: string]: AnswerPayload;
}

export interface University {
  name: string;
  region: string;
  admissionScore: string;
}

export interface RecommendedCareer {
  career: string;
  reason: string;
  universities: University[];
}

export interface MindMapBranch {
  title: string;
  items: string[];
}

export interface MindMap {
  center: string;
  branches: MindMapBranch[];
}

// --- NEW/UPDATED SIMULATION TYPES ---

// Represents a single task in the simulation
export interface SimulationTask {
  description: string;
  type: 'multiple-choice' | 'text-input';
  options?: string[];
}

// Represents the entire simulation plan generated by the AI
export interface SimulationPlan {
  career: string;
  introduction: string;
  tasks: SimulationTask[];
}

// Represents a user's answer to a task
export interface UserAnswer {
  taskDescription: string;
  answer: string;
}

// Represents the final, detailed evaluation report from the AI
export interface SimulationReport {
  strengths: string;
  improvements: string;
  competencySummary: {
    criticalThinking: number; // Score out of 10
    professionalSkills: number; // Score out of 10
    communication: number; // Score out of 10
    adaptability: number; // Score out of 10
  };
  developmentSuggestions: string[];
  refinedRecommendations: string[];
}

// This type is kept for the initial generation, but the new flow uses SimulationPlan
export interface CareerSimulation {
  career: string;
  introduction: string;
  question: string; // This can be deprecated or repurposed if needed
  choices: { text: string; nextPrompt: string; }[];
}


export interface AIResults {
  recommendedCareers: RecommendedCareer[];
  mindmap: MindMap;
  simulations: CareerSimulation[]; // This might become an array of career strings
  finalMotivation: string;
  incomeReference: string;
  supportiveAdvice: string;
}